-- Insert Education programs (13)
INSERT INTO public.programs (title, description, category, amount, timeline, eligibility_criteria, requirements, is_active) VALUES
('Pell Grant', 'Federal grant for undergraduate students with exceptional financial need who have not earned a bachelor''s degree.', 'Education', '$400-$7,395/year', '6-8 weeks', '["Undergraduate student", "Exceptional financial need", "U.S. citizen or eligible noncitizen"]', '["FAFSA completion", "Enrollment verification", "Satisfactory academic progress"]', true),
('Adult Education & GED', 'Free adult basic education and GED preparation classes for adults without high school diplomas.', 'Education', 'Free classes', '1-2 weeks', '["Age 16+", "Not enrolled in high school", "Below high school level"]', '["Age verification", "Placement test"]', true),
('After School Programs', 'Provides academic enrichment and recreational activities for students during non-school hours.', 'Education', 'Free or low-cost', '2-4 weeks', '["School-age children", "Low-income family", "Safe supervision needed"]', '["School enrollment", "Income verification", "Registration"]', true),
('Free ESL Classes', 'Free English as a Second Language classes for non-native speakers to improve English proficiency.', 'Education', 'Free classes', '1-2 weeks', '["Non-native English speaker", "Age 18+", "Commitment to attend"]', '["Placement test", "Registration", "ID"]', true),
('Job Corps (Youth Training)', 'Free education and vocational training program for young people ages 16-24.', 'Education', 'Free training + living allowance', '4-8 weeks', '["Age 16-24", "Low income", "Need additional education/training"]', '["Age verification", "Income documentation", "Application"]', true),
('Federal Work-Study Program', 'Provides part-time jobs for undergraduate and graduate students with financial need.', 'Education', 'Varies by hours worked', '4-6 weeks', '["Financial need", "Enrolled at least half-time", "U.S. citizen or eligible"]', '["FAFSA", "School enrollment", "Job placement"]', true),
('TEACH Grant', 'Grant for students who agree to teach in high-need field at low-income school for four years.', 'Education', '$4,000/year', '6-8 weeks', '["Enrolled in TEACH-eligible program", "Maintain 3.25 GPA", "Commit to teaching service"]', '["FAFSA", "Agreement to serve", "Academic records"]', true),
('Teacher Loan Forgiveness', 'Forgives up to $17,500 in federal student loans for teachers in low-income schools.', 'Education', 'Up to $17,500', '6-12 months', '["Teach 5 consecutive years", "Low-income school", "Highly qualified teacher"]', '["Teaching certification", "Employment verification", "Loan documentation"]', true),
('PSLF (Loan Forgiveness)', 'Forgives remaining federal student loan balance after 120 qualifying payments while working in public service.', 'Education', 'Remaining loan balance', '120 payments + review', '["Full-time public service employment", "Direct Loans", "120 qualifying payments"]', '["Employment certification", "Payment history", "Application"]', true),
('AmeriCorps Education Award', 'Provides education award after completing term of national service through AmeriCorps.', 'Education', '$6,895-$7,395', '10-12 months service', '["Complete AmeriCorps term", "U.S. citizen or national", "Age 17+"]', '["Service completion", "Program enrollment", "Application"]', true),
('TRIO Upward Bound', 'Prepares low-income and first-generation college students for higher education success.', 'Education', 'Free services', '2-4 weeks', '["Low income or first-generation", "Grades 9-12", "Potential for college"]', '["Income verification", "School enrollment", "Academic records"]', true),
('Perkins Career & Technical Education', 'Provides career and technical education to prepare students for high-skill, high-wage careers.', 'Education', 'Free training', '2-4 weeks', '["High school or adult student", "Career interest", "Program availability"]', '["Enrollment", "Career assessment", "Registration"]', true),
('REAP Rural Education', 'Supports rural school districts in improving teaching and learning for all students.', 'Education', 'School funding', 'Annual cycle', '["Rural school district", "Small enrollment", "Low population density"]', '["District application", "Needs assessment", "Budget proposal"]', true);

-- Insert Employment & Business programs (12)
INSERT INTO public.programs (title, description, category, amount, timeline, eligibility_criteria, requirements, is_active) VALUES
('Unemployment Insurance', 'Provides temporary income to workers who lost jobs through no fault of their own.', 'Employment & Business', '$200-$600/week', '2-3 weeks', '["Lost job through no fault", "Meet work history requirements", "Able and available to work"]', '["Employment history", "Separation documentation", "Weekly certifications"]', true),
('WIOA Job Training', 'Provides job training and employment services to help individuals gain skills for in-demand jobs.', 'Employment & Business', 'Free training', '4-8 weeks', '["Low income or barriers to employment", "Age 18+", "Legally able to work"]', '["Income verification", "Assessment", "Training plan"]', true),
('SBA Microloans', 'Small loans up to $50,000 to help small businesses and certain not-for-profit childcare centers start and grow.', 'Employment & Business', '$500-$50,000', '30-90 days', '["Small business or startup", "Unable to secure conventional financing", "Sound business plan"]', '["Business plan", "Financial statements", "Credit check"]', true),
('Vocational Rehabilitation', 'Helps people with disabilities prepare for, find, and keep employment.', 'Employment & Business', 'Free services', '2-4 weeks', '["Physical or mental disability", "Disability impacts employment", "Requires VR services"]', '["Disability documentation", "Application", "Eligibility determination"]', true),
('USDA Farm Loans', 'Provides loans to family farmers and ranchers who cannot obtain commercial credit.', 'Employment & Business', '$50,000-$600,000', '60-90 days', '["Unable to obtain commercial credit", "Farming experience", "Viable farm plan"]', '["Business plan", "Financial records", "Credit history"]', true),
('Dislocated Worker Grants', 'Provides employment and training services to workers affected by mass layoffs or plant closures.', 'Employment & Business', 'Free services', '2-4 weeks', '["Lost job due to mass layoff", "Unlikely to return to previous industry", "Eligible to work"]', '["Layoff notice", "Employment history", "Assessment"]', true),
('On-the-Job Training Subsidies', 'Reimburses employers for training costs when hiring workers who need skill development.', 'Employment & Business', '50% wage reimbursement', '4-6 weeks', '["Employer hiring eligible worker", "Provides training plan", "Commits to retention"]', '["Training plan", "Wage documentation", "Employee eligibility"]', true),
('Apprenticeship Expansion', 'Supports registered apprenticeship programs that combine on-the-job training with classroom instruction.', 'Employment & Business', 'Free training + wages', '2-6 weeks', '["Age 16+", "Meets program requirements", "Commitment to complete"]', '["Application", "Basic skills assessment", "Program acceptance"]', true),
('Workforce Reentry (Justice-Involved)', 'Provides job training and placement services to individuals with criminal records.', 'Employment & Business', 'Free services', '1-2 weeks', '["Criminal history", "Committed to employment", "Eligible to work"]', '["Background disclosure", "Assessment", "Case plan"]', true),
('Federal Bonding Program', 'Provides fidelity bonds to job seekers who have barriers to employment including criminal records.', 'Employment & Business', 'Free bond coverage', '1-2 weeks', '["At-risk job seeker", "Job offer in hand", "Barrier to employment"]', '["Job offer letter", "Employer participation", "Application"]', true),
('SBIR Grants', 'Provides research and development funding to small businesses with innovative ideas in science and technology.', 'Employment & Business', '$50,000-$1,000,000', '6-12 months', '["Small business", "U.S. owned", "Innovative R&D project"]', '["Detailed proposal", "Budget", "Company information"]', true),
('STTR Grants', 'Similar to SBIR but requires partnership between small business and research institution.', 'Employment & Business', '$50,000-$1,000,000', '6-12 months', '["Small business", "Research institution partner", "Innovative project"]', '["Partnership agreement", "Proposal", "Budget"]', true);

-- Insert remaining programs in next migration due to length...