-- Insert all Housing programs (14)
INSERT INTO public.programs (title, description, category, amount, timeline, eligibility_criteria, requirements, is_active) VALUES
('Emergency Rental Assistance', 'Provides short-term rental assistance to prevent eviction and maintain housing stability for low-income families experiencing financial hardship.', 'Housing', '$2,000-$5,000', '2-4 weeks', '["Income below 80% AMI", "Risk of eviction or homelessness", "COVID-19 financial impact"]', '["Proof of income", "Lease agreement", "Past due rent notice"]', true),
('Section 8 Housing Voucher', 'Long-term rental assistance program that helps very low-income families afford decent, safe housing in the private market.', 'Housing', '$500-$2,000/month', '6-12 months', '["Income below 50% AMI", "U.S. citizen or eligible immigrant", "Background check clearance"]', '["Income verification", "Family composition documentation", "Rental history"]', true),
('Weatherization Assistance', 'Reduces energy costs by improving home energy efficiency through insulation, heating system upgrades, and weatherproofing.', 'Housing', '$3,000-$8,000', '4-8 weeks', '["Income at or below 200% poverty level", "Homeowner or renter with landlord permission"]', '["Utility bills", "Proof of income", "Home energy audit"]', true),
('Homeowner Assistance Fund', 'Prevents mortgage delinquency and foreclosure by providing financial assistance to eligible homeowners affected by COVID-19.', 'Housing', '$10,000-$50,000', '6-12 weeks', '["Income below 150% AMI", "Experienced COVID-19 hardship", "At risk of foreclosure"]', '["Mortgage statement", "Hardship documentation", "Income proof"]', true),
('Low Income Housing Tax Credit', 'Federal tax credit program that finances development of affordable rental housing for low-income households.', 'Housing', 'Varies by development', '12-24 months', '["Income below 60% AMI", "Meet specific income limits per household size"]', '["Income certification", "Household size verification", "Application through property"]', true),
('Section 504 Home Repair', 'Provides loans and grants to very low-income homeowners to repair, improve, or modernize their homes in rural areas.', 'Housing', '$7,500-$20,000', '8-16 weeks', '["Age 62+ for grants", "Income below 50% AMI", "Own and occupy home in rural area"]', '["Property ownership proof", "Income documentation", "Repair estimates"]', true),
('Lead Paint Removal', 'Provides funding to identify and remove lead-based paint hazards from homes with young children.', 'Housing', '$5,000-$15,000', '6-10 weeks', '["Built before 1978", "Children under 6 in household", "Low to moderate income"]', '["Lead inspection report", "Proof of occupancy", "Income verification"]', true),
('Public Housing Authority (PHA) Rentals', 'Provides decent and safe rental housing for eligible low-income families, elderly, and persons with disabilities.', 'Housing', '30% of income', '3-12 months', '["Very low income", "U.S. citizen or eligible immigrant", "Pass background check"]', '["Income documentation", "ID verification", "Rental history"]', true),
('Homelessness Prevention Program', 'Rapidly re-houses homeless individuals and families while promoting long-term housing stability.', 'Housing', '$3,000-$10,000', '2-6 weeks', '["At imminent risk of homelessness", "Income below 30% AMI", "Lack resources to obtain housing"]', '["Eviction notice or termination letter", "Income proof", "Case management participation"]', true),
('Mortgage Assistance for Unemployed', 'Temporary mortgage payment assistance for homeowners who lost employment through no fault of their own.', 'Housing', '$1,500-$3,000/month', '3-12 months', '["Unemployed due to involuntary job loss", "Receiving unemployment benefits", "Owner-occupied home"]', '["Unemployment verification", "Mortgage statement", "Previous employment proof"]', true),
('USDA Rural Housing Direct Loans (502)', 'Helps low-income rural residents purchase, build, repair, or renovate decent, safe, and sanitary housing.', 'Housing', '$100,000-$300,000', '60-90 days', '["Income below 80% AMI", "Unable to obtain conventional credit", "Rural area residence"]', '["Credit history", "Income verification", "Property appraisal"]', true),
('HUD Good Neighbor Next Door', 'Offers law enforcement officers, teachers, firefighters, and EMTs a 50% discount on homes in revitalization areas.', 'Housing', '50% off list price', '30-60 days', '["Full-time employee in eligible profession", "Commit to live in home 3 years", "Purchase in revitalization area"]', '["Employment verification", "Commitment agreement", "Pre-qualification letter"]', true),
('Emergency Home Repairs Program', 'Provides emergency grants for critical home repairs to prevent immediate health and safety hazards.', 'Housing', '$1,000-$5,000', '1-3 weeks', '["Low income household", "Owner-occupied", "Critical safety issue"]', '["Ownership proof", "Contractor estimates", "Income verification"]', true),
('Manufactured Housing Assistance', 'Helps low-income families purchase or refinance manufactured homes in rural areas.', 'Housing', '$50,000-$100,000', '45-60 days', '["Rural area location", "Income below 115% AMI", "Credit worthy"]', '["Income documentation", "Credit report", "Property details"]', true);

-- Insert all Food programs (13)
INSERT INTO public.programs (title, description, category, amount, timeline, eligibility_criteria, requirements, is_active) VALUES
('SNAP (Food Stamps)', 'Provides monthly benefits to help low-income individuals and families buy the food they need for good health.', 'Food', '$200-$800/month', '30 days', '["Income below 130% poverty level", "Resource limits met", "Work requirements for able-bodied adults"]', '["ID verification", "Income proof", "Household size documentation"]', true),
('WIC', 'Provides nutritious foods, nutrition education, and healthcare referrals to low-income pregnant women, new mothers, and young children.', 'Food', '$50-$150/month', '2-4 weeks', '["Pregnant, postpartum, or breastfeeding women", "Children under 5", "Income below 185% poverty level"]', '["Proof of residency", "Income documentation", "Medical/nutritional risk assessment"]', true),
('School Lunch Program', 'Provides free or reduced-price lunches to students from low-income families during the school year.', 'Food', 'Free or $0.40/lunch', '2-3 weeks', '["Family income below 185% poverty level for reduced", "Below 130% for free"]', '["School enrollment", "Income verification", "Application form"]', true),
('Senior Nutrition', 'Provides nutritious meals to seniors 60+ at community sites or through home delivery (Meals on Wheels).', 'Food', 'Free meals', 'Immediate-2 weeks', '["Age 60 or older", "Spouse of any age", "Disabled under 60 with senior"]', '["Age verification", "Needs assessment"]', true),
('Emergency Food Assistance', 'Provides emergency food and nutrition assistance to low-income individuals through food banks and pantries.', 'Food', 'Food boxes monthly', 'Same day-1 week', '["Income below 150% poverty level", "Demonstrated need"]', '["Proof of residency", "Income documentation"]', true),
('Summer Food Service', 'Provides free meals to children from low-income areas when school is not in session during summer months.', 'Food', 'Free meals', 'Summer months', '["Children 18 and under", "Located in low-income area"]', '["Age verification", "Participation in program site"]', true),
('Double Up Food Bucks', 'Matches SNAP benefits dollar-for-dollar (up to $20) when purchasing fresh fruits and vegetables at farmers markets.', 'Food', 'Up to $20/day match', 'Immediate', '["Active SNAP recipient", "Shopping at participating market"]', '["SNAP EBT card", "Purchase of eligible produce"]', true),
('Meals on Wheels', 'Delivers nutritious meals directly to homebound seniors who have difficulty shopping or cooking.', 'Food', 'Free or low-cost meals', '1-2 weeks', '["Age 60+", "Homebound or mobility limited", "Unable to prepare meals"]', '["Age verification", "Needs assessment", "Doctor recommendation"]', true),
('Food Pantry Vouchers', 'Provides vouchers for emergency food assistance at local food pantries and distribution centers.', 'Food', '$50-$200/month', 'Same day-3 days', '["Income below 200% poverty level", "Emergency situation"]', '["ID verification", "Proof of need"]', true),
('Tribal Food Distribution (FDPIR)', 'Provides commodity foods to low-income households living on Indian reservations and to Native American families.', 'Food', 'Monthly food package', '2-4 weeks', '["Live on reservation or approved area", "Income below 133% poverty level", "Cannot participate in SNAP"]', '["Tribal enrollment", "Income verification", "Residency proof"]', true),
('Community Gardens Grants', 'Supports community gardens that provide fresh produce to low-income neighborhoods and food deserts.', 'Food', '$500-$5,000', '4-8 weeks', '["Nonprofit or community organization", "Serve low-income area", "Sustainable plan"]', '["Organization documentation", "Garden plan", "Budget proposal"]', true),
('Free Breakfast for Kids', 'Provides free breakfast to students from low-income families at participating schools before classes begin.', 'Food', 'Free breakfast', '2-3 weeks', '["School enrollment", "Family income below 130% poverty level"]', '["Income verification", "School registration"]', true),
('Senior Farmers Market Nutrition', 'Provides low-income seniors with coupons to purchase fresh fruits, vegetables, and herbs at farmers markets.', 'Food', '$20-$50/year', 'Seasonal', '["Age 60+", "Income below 185% poverty level"]', '["Age verification", "Income documentation"]', true);

-- Insert all Healthcare programs (18)
INSERT INTO public.programs (title, description, category, amount, timeline, eligibility_criteria, requirements, is_active) VALUES
('Medicaid', 'Provides free or low-cost health coverage to eligible low-income adults, children, pregnant women, elderly, and people with disabilities.', 'Healthcare', 'Full coverage', '30-45 days', '["Income below 138% poverty level", "U.S. citizen or eligible immigrant", "State residency"]', '["Proof of income", "ID verification", "Citizenship documentation"]', true),
('CHIP', 'Provides low-cost health coverage to children in families that earn too much to qualify for Medicaid but cannot afford private insurance.', 'Healthcare', '$0-$50/month', '2-4 weeks', '["Children under 19", "Family income too high for Medicaid", "Uninsured"]', '["Income verification", "Child''s birth certificate", "Proof of residency"]', true),
('Medicare Extra Help', 'Helps pay Medicare prescription drug costs including premiums, deductibles, and copayments for people with limited income.', 'Healthcare', '$1,000-$5,000/year', '3-6 weeks', '["Medicare recipient", "Income below $21,870 (single)", "Limited resources"]', '["Medicare card", "Income documentation", "Asset verification"]', true),
('Community Mental Health Services', 'Provides mental health services including counseling, therapy, and psychiatric care on a sliding fee scale.', 'Healthcare', '$0-$50/visit', '1-2 weeks', '["Low to moderate income", "Mental health need", "Community resident"]', '["Income verification", "Referral or self-assessment"]', true),
('Substance Abuse Treatment', 'Provides free or low-cost treatment for drug and alcohol addiction including counseling and medication-assisted treatment.', 'Healthcare', '$0-$100/month', '1-3 weeks', '["Substance use disorder diagnosis", "Low income", "Commitment to treatment"]', '["Assessment", "Income verification", "Treatment plan agreement"]', true),
('Medicare Savings Program', 'Helps pay Medicare premiums and may cover deductibles and coinsurance for people with limited income.', 'Healthcare', '$200-$500/month', '4-6 weeks', '["Medicare Part A", "Income below specific limits", "Limited resources"]', '["Medicare card", "Income proof", "Resource documentation"]', true),
('Healthy Start', 'Provides prenatal care, parenting education, and support services to reduce infant mortality in high-risk communities.', 'Healthcare', 'Free services', '1-2 weeks', '["Pregnant or postpartum up to 2 years", "Reside in target area", "At-risk pregnancy"]', '["Pregnancy verification", "Residency proof", "Medical records"]', true),
('Nurse-Family Partnership', 'Pairs first-time mothers with registered nurses for home visits from pregnancy through child''s second birthday.', 'Healthcare', 'Free services', '2-4 weeks', '["First-time mother", "Low income", "Pregnant (before 28 weeks)"]', '["Pregnancy verification", "Income documentation", "Commitment to program"]', true),
('Community Dental Services', 'Provides dental care including cleanings, fillings, and extractions on a sliding fee scale or free for qualifying individuals.', 'Healthcare', '$0-$75/visit', '1-3 weeks', '["Low income", "No dental insurance", "Community resident"]', '["Income verification", "Residency proof"]', true),
('Free Clinics Grant Program', 'Supports free and charitable clinics that provide healthcare to uninsured and underinsured individuals.', 'Healthcare', 'Free services', 'Immediate-1 week', '["Uninsured or underinsured", "Income below 200% poverty level"]', '["Income verification", "Insurance status proof"]', true),
('State Children''s Health Insurance Pool', 'High-risk pool providing health insurance to children denied coverage due to pre-existing conditions.', 'Healthcare', '$25-$100/month', '4-6 weeks', '["Under 19", "Denied private insurance", "State resident"]', '["Denial letter", "Medical documentation", "Proof of residency"]', true),
('Vaccines for Children (VFC)', 'Provides free vaccines to children who might not otherwise be vaccinated due to inability to pay.', 'Healthcare', 'Free vaccines', 'Immediate', '["Age 18 or younger", "Medicaid eligible, uninsured, or underinsured"]', '["Age verification", "Insurance status"]', true),
('Ryan White HIV/AIDS Program', 'Provides medical care, medications, and support services to people living with HIV who are uninsured or underinsured.', 'Healthcare', 'Full coverage', '2-4 weeks', '["HIV positive", "Low income", "Uninsured or underinsured"]', '["HIV diagnosis", "Income verification", "Medical records"]', true),
('Indian Health Service', 'Provides comprehensive health services to American Indians and Alaska Natives.', 'Healthcare', 'Free services', 'Immediate-2 weeks', '["Federally recognized tribe member", "Descendant of tribe member"]', '["Tribal enrollment documentation", "Certificate of Indian Blood"]', true),
('Rural Health Clinic Assistance', 'Supports rural health clinics providing primary care and emergency services in underserved rural areas.', 'Healthcare', 'Sliding scale', '1-2 weeks', '["Rural area resident", "Low to moderate income"]', '["Residency proof", "Income documentation"]', true),
('Telehealth Subsidy Program', 'Provides subsidized virtual healthcare visits for low-income individuals in underserved areas.', 'Healthcare', '$0-$20/visit', 'Immediate', '["Low income", "Limited healthcare access", "Internet connection"]', '["Income verification", "Technology access"]', true),
('Vision Assistance (Glasses for Kids)', 'Provides free eye exams and glasses to low-income children to ensure vision health and academic success.', 'Healthcare', 'Free exam & glasses', '2-4 weeks', '["School-age children", "Family income below 200% poverty level", "Need for vision correction"]', '["School enrollment", "Income verification", "Eye exam"]', true),
('Hearing Aid Assistance', 'Provides financial assistance for hearing aids and related services to low-income individuals with hearing loss.', 'Healthcare', '$500-$3,000', '4-8 weeks', '["Documented hearing loss", "Low income", "No insurance coverage for devices"]', '["Audiological evaluation", "Income verification", "Medical necessity documentation"]', true);

-- Insert all Utilities programs (10)
INSERT INTO public.programs (title, description, category, amount, timeline, eligibility_criteria, requirements, is_active) VALUES
('LIHEAP', 'Assists low-income households with energy bills, weatherization, and energy-related home repairs.', 'Utilities', '$200-$1,000', '4-8 weeks', '["Income at or below 150% poverty level", "U.S. citizen or legal resident"]', '["Utility bills", "Income verification", "Social Security numbers"]', true),
('Affordable Connectivity Program', 'Provides discount of up to $30/month on internet service for eligible low-income households.', 'Utilities', '$30/month', '2-3 weeks', '["Income below 200% poverty level", "Participate in certain assistance programs", "Received Pell Grant"]', '["Income proof or program participation", "Application form"]', true),
('Lifeline Free Phone', 'Provides free or discounted phone service to ensure low-income consumers can afford basic telephone service.', 'Utilities', 'Free service or $9.25/month discount', '1-2 weeks', '["Income below 135% poverty level", "Participate in qualifying program"]', '["Income documentation or program participation proof"]', true),
('Water Bill Assistance', 'Helps low-income households pay water and sewer bills to prevent service disconnection.', 'Utilities', '$100-$500', '2-6 weeks', '["Income below 150% poverty level", "Past due water bill", "Homeowner or tenant"]', '["Utility bill", "Income verification", "Residency proof"]', true),
('Emergency Broadband Benefit', 'Emergency program providing discounts on broadband service and connected devices during qualifying crisis periods.', 'Utilities', '$50/month + $100 device', '2-4 weeks', '["Substantial loss of income due to job loss", "Household income below 135% poverty", "Received Pell Grant"]', '["Income documentation", "Job loss verification or program participation"]', true),
('State Weather Relief (Cooling Centers)', 'Provides access to air-conditioned facilities during extreme heat and fans or cooling assistance for vulnerable populations.', 'Utilities', 'Free access or $50-$200', 'Immediate', '["Low income", "Age 60+, young children, or health conditions", "Extreme heat event"]', '["Residency proof", "Age or medical documentation"]', true),
('Utility Shutoff Protection', 'Protects vulnerable households from utility disconnection during extreme weather or medical emergencies.', 'Utilities', 'Service protection', 'Immediate-1 week', '["Seriously ill household member", "Extreme weather period", "Low income"]', '["Medical certification", "Utility account info", "Income verification"]', true),
('Solar Assistance Grants', 'Provides grants or incentives for low-income households to install solar panels and reduce energy costs.', 'Utilities', '$2,000-$10,000', '8-16 weeks', '["Homeowner", "Income below 80% AMI", "Suitable property for solar"]', '["Ownership proof", "Income documentation", "Property assessment"]', true),
('Emergency Propane & Fuel Aid', 'Provides emergency assistance with propane, heating oil, or other home heating fuel costs during winter months.', 'Utilities', '$200-$800', '1-3 weeks', '["Income below 150% poverty level", "Heating emergency", "Primary heat source"]', '["Fuel bill or quote", "Income verification", "Emergency documentation"]', true),
('Utility Reconnection Fee Waivers', 'Waives reconnection fees for low-income households reconnecting utility service after disconnection.', 'Utilities', '$50-$150 waiver', '1-2 weeks', '["Low income", "Recently disconnected service", "Payment arrangement made"]', '["Income verification", "Utility account", "Payment plan agreement"]', true);

-- Insert Childcare & Family programs (11)
INSERT INTO public.programs (title, description, category, amount, timeline, eligibility_criteria, requirements, is_active) VALUES
('Child Care Subsidy', 'Helps low-income working families pay for child care so parents can work or attend school.', 'Childcare & Family', '$200-$1,000/month', '4-6 weeks', '["Working or in school", "Income below 85% SMI", "Children under 13"]', '["Employment/school verification", "Income proof", "Child information"]', true),
('Head Start', 'Provides comprehensive early childhood education, health, nutrition, and parent involvement services to low-income children and families.', 'Childcare & Family', 'Free services', '2-8 weeks', '["Income below poverty level", "Children ages 3-5", "Family in crisis or homeless"]', '["Income documentation", "Child''s birth certificate", "Immunization records"]', true),
('Foster Care Support', 'Provides monthly payments and support services to foster families caring for children removed from their homes.', 'Childcare & Family', '$500-$1,500/month', '4-8 weeks', '["Licensed foster parent", "Caring for eligible child", "Completed training"]', '["Foster license", "Child placement documentation", "Home study"]', true),
('Adoption Assistance', 'Provides monthly payments and medical assistance to families adopting children with special needs from foster care.', 'Childcare & Family', '$400-$1,000/month', '6-12 weeks', '["Adopting special needs child", "Child eligible for assistance", "Income requirements vary"]', '["Adoption documentation", "Child''s special needs certification", "Application"]', true),
('TANF (Temporary Assistance)', 'Provides temporary cash assistance to families with children to help them achieve economic self-sufficiency.', 'Childcare & Family', '$200-$600/month', '30-45 days', '["Dependent children in household", "Very low income", "Meet work requirements"]', '["Income verification", "Child documentation", "Work participation plan"]', true),
('CCDF Child Care Fund', 'Federal funding that helps states subsidize child care for low-income families.', 'Childcare & Family', 'Varies by state', '4-8 weeks', '["Income below state threshold", "Working or in training", "Children under 13"]', '["Income proof", "Work/training verification", "Child care provider info"]', true),
('Parenting Skills Training', 'Provides free parenting classes and family support services to strengthen families and prevent child abuse.', 'Childcare & Family', 'Free classes', '1-2 weeks', '["Parent or caregiver", "Desire to improve parenting skills"]', '["Registration", "Commitment to attend"]', true),
('Family Preservation Services', 'Provides intensive in-home services to families in crisis to prevent out-of-home placement of children.', 'Childcare & Family', 'Free services', '1-2 weeks', '["Child at imminent risk of removal", "Family willing to participate", "Safety can be maintained"]', '["Referral from child welfare", "Safety assessment", "Service plan agreement"]', true),
('Kinship Care Support', 'Provides financial and support services to relatives caring for children when parents cannot.', 'Childcare & Family', '$300-$800/month', '4-6 weeks', '["Relative caregiver", "Child cannot live with parents", "Income requirements vary"]', '["Relationship proof", "Child custody/guardianship", "Income documentation"]', true),
('Child Health Plus', 'Comprehensive health insurance for children in families earning too much for Medicaid but unable to afford private insurance.', 'Childcare & Family', '$0-$60/month', '2-4 weeks', '["Children under 19", "Income too high for Medicaid", "Uninsured"]', '["Income verification", "Child''s information", "Residency proof"]', true),
('Children''s Behavioral Health', 'Provides mental health services including therapy and counseling for children with emotional or behavioral challenges.', 'Childcare & Family', '$0-$50/session', '1-3 weeks', '["Child with behavioral/mental health needs", "Low to moderate income"]', '["Assessment", "Income verification", "Parental consent"]', true);

-- Continue in next query...